language: python

sudo: required
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential python3-dev xvfb python3-pyqt5.qtmultimedia
  
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.5
        env: TOX_ENV=flake8
      - python: 3.5
        env: TOX_ENV=coverage

install:
  - pip install tox
  - sudo apt-get install upx git qt5-qmake qttools5-dev-tools libqt5sql5-sqlite unrar-free

script:
- tox -e ${TOX_ENV}
- python setup.py build_pro
- python setup.py build_ui
- python setup.py build_deb
- sudo dpkg -i pynocchio*.deb

deploy:
  provider: releases
  api_key :  $GITHUB_OAUTH_TOKEN 
     file : "pynocchio_2.2.1_amd64.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: pynocchio/pynocchio
    branch: master

after_success:
 - coveralls
